Removed style applyed on .ui.container
eea/volto-banner pull request #11
Opened 2021-10-22 15:33 UTC by razvanMiu

2021-10-25 08:48 UTC, ichim-david submitted a review, later dismissed

2021-11-04 13:15 UTC, avoinea approved these changes

2021-11-04 13:17 UTC, avoinea requested changes
https://user-images.githubusercontent.com/323385/140320043-d4bc4da7-240a-4718-8ee9-7a310c688584.mp4

2021-11-04 13:18 UTC, avoinea commented
@razvanMiu See previous comment for padding issue on lower resolutions

2021-11-10 11:01 UTC, ichim-david approved these changes

2021-11-10 11:02 UTC, merged